name: motion_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  get: ^4.6.5

flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "00623B"
  image: "assets/images/fullLogo.png"

  android_12:
    color: "00623B"
    image: "assets/images/fullLogo2.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
